import { inngest } from '../../Config/inngest.js';
import { Quiz } from '../../Models/quiz.model.js';
import { cleanTempFile } from '../../Utils/cleanTempFile.js';
import { extractText } from '../../Utils/parsePdf.js';
import { cleanRawText } from '../../Utils/cleanText.js';
import {
  generateQuiz,
  generateTranscript,
} from '../../Services/ai.services.js';
import { downloadYoutubeMp3 } from '../../Utils/downloadYoutubeMp3.js';

const onCreateQuiz = inngest.createFunction(
  {
    id: 'on-quiz-create',
    retries: 0,
  },
  { event: 'quiz/create' },
  async ({ event, step }) => {
    const { quizId } = event.data;
    try {
      // Pipeline starts

      const quiz = await step.run('get-quiz-document-object', async () => {
        const quizDoc = await Quiz.findById(quizId);
        quizDoc.status = 'processing';
        await quizDoc.save();
        return quizDoc;
      });
      console.log('Quiz Fetched succesfully ');

      if (quiz.sourceType === 'pdf') {
        //Pipeline For pdf
        console.log('Inside pfd pipeline');

        const rawText = await step.run('extract-text-from-pdf', async () => {
          return await extractText(quiz.pdfPath);
        });
        const cleanText = await step.run('clean-rawText', async () => {
          return await cleanRawText(rawText);
        });
        //Call LLM to generate quiz
        const quizQuestions = await step.run('generate-quiz', async () => {
          return await generateQuiz({
            text: cleanText,
            difficulty: quiz.difficulty,
          });
        });

        await step.run('save-quizQuestions-to-db', async () => {
          await Quiz.findByIdAndUpdate(quizId, {
            questions: quizQuestions,
            generatedAt: Date.now(),
            status: 'completed',
            pdfPath: undefined,
          });
        });

        await step.run('clean-temp-pdf', async () => {
          await cleanTempFile(quiz.pdfPath);
        });
      } else {
        //Pipeline For youtubeVideo
        console.log('Inside youtube video pipeline');

        const { filePath } = await step.run(
          'download-youtube-audio-mp3',
          async () => {
            return await downloadYoutubeMp3(quiz.youtubeUrl);
          }
        );

        console.log('Extracted File Path : ', filePath);

        await step.run('update-youtubeMp3Path-and-status-to-db', async () => {
          await Quiz.findByIdAndUpdate(quizId, {
            youtubeMp3Path: filePath,
            status: 'processing',
          });
        });

        console.log('Updated temp mp3 filePath to  database');

        const rawText = await step.run('generate-transcribe', async () => {
          return await generateTranscript(filePath);
        });

        console.log('Transcript generated succesfully from the mp3');

        const cleanText = await step.run('clean-rawText', async () => {
          return await cleanRawText(rawText);
        });

        console.log('Cleaning the Transcript generated succesfully ');
        //Call LLM to generate quiz
        const quizQuestions = await step.run('generate-quiz', async () => {
          return await generateQuiz({
            text: cleanText,
            difficulty: quiz.difficulty,
          });
        });
        console.log(
          'Quiz questions generated by the LLM   : ',
          quizQuestions.questions
        );

        await step.run('save-quizQuestions-to-db', async () => {
          await Quiz.findByIdAndUpdate(quizId, {
            questions: quizQuestions.questions,
            generatedAt: Date.now(),
            status: 'completed',
            youtubeMp3Path: undefined,
          });
        });
        console.log('Saved the questions to database sucesfully');

        // await step.run('clean-temp-pdf', async () => {
        //   await cleanTempFile(filePath);
        // });

        // console.log('Temp audio file cleaned succesfully');
      }

      return { success: true };
    } catch (error) {
      console.error('Error in running the pipeline : ', error.message);

      //   const quiz = await Quiz.findByIdAndUpdate(quizId, { status: 'failed' });

      //   try {
      //     if (quiz.sourceType === 'pdf') {
      //       if (quiz.pdfPath) {
      //         await cleanTempFile(quiz.pdfPath);
      //       }
      //     } else {
      //       if (quiz.youtubeMp3Path) {
      //         await cleanTempFile(quiz.youtubeMp3Path);
      //       }
      //     }
      //   } catch (cleanupError) {
      //     console.error('Failed to clean temp file:', cleanupError.message);
      //   }
      //   return { success: false };
    }
  }
);

export { onCreateQuiz };
